### ISSUE TITLE
People subcategories

### ISSUE THREAD

**Issue by denizyuret** [kuisailab/ai-media-group#11]
Let's create some subcategories under people and have multiple people pages. We need to get the photo, title (Prof, dekan, vp etc), homepage, lab page (if there is one), research areas etc. for each of these people from their websites. In the future we can increase this creating a page for alumni, board of advisees etc. Here is my suggestion:

**People/Board of Directors:** 
* Deniz Yuret (Director)
* Özgür Barış Akan
* Aylin Küntay
* İhsan Solaroğlu
* Zeynep Gürhan Canlı

**People/AI Committee:** A subset of people under ai.ku.edu.tr/people will go here:
* Alper T. Erdoğan
* Attila Gürsoy
* Barış Akgün
* Çağatay Başdoğan
* Deniz Yuret
* Didem Unat
* Engin Erzin
* Fatma Güney
* Metin Sezgin
* Murat Tekalp
* Öznur Özkasap
* Yücel Yemez
* Zafer Doğan

**People/Affiliated Faculty:** We will group people on this page by department/faculty/school etc. then alphabetically by first name. The people in the above list will be repeated here, but this will be a full list of affiliated researchers.  Here is the initial list:

Computer Engineering
* Attila Gürsoy
* Alptekin Küpcü
* Barış Akgün
* Deniz Yuret
* Didem Unat
* Engin Erzin
* Fatma Güney
* Metin Sezgin
* Öznur Özkasap
* Yücel Yemez

Electrical and Electronics Engineering
* Alper T. Erdoğan
* Murat Tekalp
* Onur Ergen
* Sinem Çöleri Ergen
* Zafer Doğan

Mechanical Engineering
* Çağatay Başdoğan
* Demircan Canadinç
* Mehmet Sayar

Industrial Engineering
* Barış Tan
* Fikri Karaesmen
* Metin Türkay

Chemical and Biological Engineering
* Can Erkey
* Özlem Keskin Özkaya
* Seda Keskin Avcı

College of Sciences
* Alkan Kabakçıoğlu
* Aşkın Kocabaş

College of Social Sciences and Humanities
* Aylin Küntay
* Erdem Yörük
* Tilbe Göksun

College of Administrative Sciences and Economics
* Serpil Sayın

Bogazici University
* Arkadaş Özakın
* Burak Acar

Hacettepe University
* Aykut Erdem
* Erkut Erdem

**Comment by denizyuret** [comment]
Please do this as a draft and share with me before publishing.

**Comment by NursenaKoprucu** [comment]
Okay, it is almost done. We will share it until Sunday.

Nursena

denizyuret <notifications@github.com>, 26 Haz 2020 Cum, 11:10 tarihinde
şunu yazdı:

**Comment by EgeD** [comment]
Deniz Hocam, I have finished doing the 3 individual pages, they are on draft. According to your Feedbacks on the pages I will arrange their links and publish them

**Comment by denizyuret** [comment]
Thanks Ege, some minor comments:

1. We should talk about the new menu structure, what people click on to get
to various pages.
2. Let's add Cagatay Basdogan hoca to AI committee as well.
3. Board of directors: Aylin Kuntay is the Dean of the College of Social
Sciences and Humanities, Zeynep Gurhan Canli is the dean of College of
Administrative Sciences and Economics, Ihsan Solaroglu is the director of
KUTTAM, let's add these to their titles. Karismasin diye benimkinin yanina
da Director, KUIS AI Lab diyebiliriz.
4. Bazilarinda Prof. bazilarinda Prof. Dr. demisiz, consistent olarak Prof.
Dr. kullanalim.
5. Homepage'leri yok bazi proflarin, bulup ekleyelim consistent olarak.
6. Affiliated faculty: bu sayfa dogal olarak uzun ve daha da uzayacak. Daha
kolay navigate edilebilmesi icin bir cozum dusunelim: resimleri yanyana
dizen daha tight bir format kullanilabilir, tepeye bir table of contents
eklenebilir, collapse/expand eden section'lar olabilir. MAVA'dan gelen style suggestions varsa onlari da dikkate alalim.

**Comment by denizyuret** [comment]
Once we are done with faculty, we should start working on an alumni page as well...

**Comment by metocusu** [comment]
@EgeD Can you let me know when the pages are ready to review. Please include their links as well...

**Comment by EgeD** [comment]
I have done all of the revisions but I haven't done the first one because I thought that as the menus in the left we could place Affiliated Faculty, AI Committee and Board of Directors but in order to do that I have to publish the pages and create menu with these pages. If that's okay I will create a menu like that and place it on the left after the pages are published. Here are the list of the pages:

Board of Directors:
https://ai.ku.edu.tr/people-boardofdirectors/
AI Committee:
https://ai.ku.edu.tr/people-ai-committee/
Affiliated Faculty:
https://ai.ku.edu.tr/people-affiliated-faculty/

**Comment by denizyuret** [comment]
Eline saglik Ege, gayet guzel olmus. Publish edebilirsin, menu yapisini
olustur, sonra birlikte bakalim.

Board of Directors sayfasinda Ihsan Solaroglu'nun ismi yanlis yazilmis, bir
de bolum olarak "School of Medicine" ekleyelim. Ayni sayfada bana da bolum
olarak "Department of Computer Engineering" ekleyelim.

tesekkurler,
deniz

**Comment by denizyuret** [comment]
Ege, son bir iki duzeltmeyi de yapip bu sayfalari publish edebilir miyiz
lutfen.

**Comment by EgeD** [comment]
Merhaba Deniz Hocam, kusura bakmayın ilgilenemedim öncesinde. Gün içerisinde düzeltmeleri yapıp publish edeceğim

**Comment by EgeD** [comment]
Son düzeltmeleri de yapıp sayfaları publishledim

**Comment by denizyuret** [comment]
Tesekkurler.

**Comment by fguney** [comment]
We can close this issue @denizyuret Hocam?
