### ISSUE TITLE
Create an alumni page under people.

### ISSUE THREAD

**Issue by denizyuret** [kuisailab/ai-media-group#12]

**Comment by fguney** [comment]
@begyalcin we can work on this next?

**Comment by begyalcin** [comment]
Okay sure

Begüm Yalçın

**Comment by fguney** [comment]
@denizyuret Hocam, alumni ile ilgili su an nerde olduklari, fotolari gibi bilgileri bir yerde topladik mi hic? Yoksa mail atip istememiz gerekecek.

**Comment by denizyuret** [comment]
Henuz toplamadik, benimkiler homepage’imde Students altinda.
