### ISSUE TITLE
Prepare FAQ based on Webinar questions

### ISSUE THREAD

**Issue by denizyuret** [kuisailab/ai-media-group#3]

**Comment by metocusu** [comment]
Begum or Necla, can you please prepare an empty FAQ page that I can then fill in. Don't link it to the AI page yet. Share the link with me please.

**Comment by nmutlu98** [comment]
I created an faq page in the test page. You can fill it from this link. [https://ai.test.ku.edu.tr/frequently-asked-questions/](url) Note that the side menu that I added to the page can change when we link it to a menu in the main page.

**Comment by metocusu** [comment]
Necla, can you create the page on the main ai page, not the test one. I believe IT has not given me  permission to edit the test pages.

**Comment by nmutlu98** [comment]
I created it. You can access it through this link I guess [https://ai.ku.edu.tr/?page_id=1200&preview=true](url)

**Comment by metocusu** [comment]
Necla,

I'm getting a page not found error.

T. Metin Sezgin, PhD

Associate Professor
Koc University
College of Engineering
Istanbul, Turkey

http://iui.ku.edu.tr

**Comment by nmutlu98** [comment]
As it was a draft, probably we could not share the link for it, although it could have been seen among the pages of the main page. Just to be safe, I hadn't published it last night. Now, I published it without linkink to somewhere in the main page. Here is the link: [https://ai.ku.edu.tr/frequently-asked-questions/](url)

**Comment by metocusu** [comment]
Thanks...

T. Metin Sezgin, PhD

Associate Professor
Koc University
College of Engineering
Istanbul, Turkey

http://iui.ku.edu.tr

**Comment by metocusu** [comment]
Bora, can you add the questions highlighted in red to the FAQ document. Feel free to delegate to the members of the content group and open/assign a new issue.

[KUIS AI LAB 14.05.2020 Webinar Q&A Report MA comments.xlsx](https://github.com/kuisailab/ai-media-group/files/4640047/KUIS.AI.LAB.14.05.2020.Webinar.Q.A.Report.MA.comments.xlsx)

**Comment by msanuk17** [comment]
I'm on it.

**Comment by metocusu** [comment]
Bora, any progress on this?

**Comment by msanuk17** [comment]
I added the red questions (that had answers) to the FAQ page.

**Comment by metocusu** [comment]
The initial FAQ document is ready. Can the content team please put a link
to it from an appropriate place in the AI Lab page.

T. Metin Sezgin, PhD

Associate Professor
Koc University
College of Engineering
Istanbul, Turkey

http://iui.ku.edu.tr

**Comment by nmutlu98** [comment]
We added a seperate menu item for it, called "FAQ", to the main menu.
