### ISSUE TITLE
some material for the machine learning page

### ISSUE THREAD

**Issue by denizyuret** [kuisailab/ai-media-group#35]
In the left side menu, I don't quite understand how the publication buttons work. From homepage I click on Research, Machine Learning and I am at "Home | Research | Machine Learning", ok. Then I click on "Research Highlights" and that's also ok. But if I click on the "Publications" box, it takes me to "Home | Publications | Latest Publications" with a bunch of years on the left but no mention of "Machine Learning" or my position in the menu tree. If I then click on "Publications" in "Home | Publications" then I get a general publication page with all the topics on the left (not years this time). Then if I click on "Machine Learning" I get the publications page for Multimedia. So something is off.

Here is a Knet poster for research highlights:

http://www.denizyuret.com/2016/12/knet-beginning-deep-learning-with-100.html

or a talk video (you guys pick one):

http://www.denizyuret.com/2017/05/juliacon-2017-berkeley-june-20-24.html

Here are some papers we can add to machine learning publications:

```
@inproceedings{yuret2016knet,
    year = {2016},
    keywords = {ai.ku},
    author = {Yuret, Deniz},
    month = {December},
    booktitle = {Machine Learning Systems Workshop at NIPS 2016},
    url = {/bib/yuret/yuret2016knet/knet-beginning-deep%20%283%29.pdf,https://goo.gl/KeOEoJ},
    title = {Knet: beginning deep learning with 100 lines of {Julia}},
}

@inproceedings{coban2017,
    author = {{\c{C}}oban, Enis Berk and Yuret, Deniz and Unat, Didem},
    booktitle = {5. Ulusal Y{\"u}ksek Ba{\c{s}}ar{\i}ml{\i} Hesaplama Konferans{\i}},
    year = {2017},
    address = {{\.I}stanbul},
    month = {September},
    keywords = {ai.ku},
    url = {/bib/coban/coban2017/paper.pdf,https://drive.google.com/file/d/0B5_wxKFQbOTMbXVzTWhsbGFrZnM/view?usp=sharing},
    title = {Multidimensional Broadcast Operation on the {GPU}},
}

@article{dikbayir2018,
    author = {Dikbay{\i}r, Do\u{g}a and \c{C}oban, Enis Berk and Kesen, \.Ilker and Yuret, Deniz and Unat, Didem},
    journal = {Concurrency and Computation: Practice and Experience},
    year = {2018},
    keywords = {ai.ku},
    title = {Fast Multidimensional Reduction and Broadcast Operations on {GPU} for Machine Learning},
    url = {https://doi.org/10.1002/cpe.4691,/bib/dikbayir/dikbayir2018/Dikbay-r_et_al-2018-Concurrency_and_Computation%253A_Practice_and_Experience.pdf},
    month = {May},
}

@inproceedings{Innes2018,
    title = {On Machine Learning and Programming Languages},
    booktitle = {SysML Conference},
    year = {2018},
    url = {http://www.sysml.cc/doc/37.pdf,http://www.sysml.cc/},
    keywords = {ai.ku},
    address = {Stanford, CA},
    month = {Feb},
    author = {Innes, Mike and Yuret, Deniz and others},
}
```

**Comment by fguney** [comment]
@NursenaKoprucu you can work on this maybe :)

**Comment by NursenaKoprucu** [comment]
I added Knet to both Machine Learning and NLP research highlights. (If it is wrong, I can remove it.) I realized that there are some minor differences between research highlight pages (e.g. one is left-aligned, another one is center-aligned). I wrote Birkan for this and we will update them. 
I could not figure out the publication page. Necla will work on that problem.

**Comment by nmutlu98** [comment]
I fixed the link redirecting to the machine learning publications and added the publications to the page.

**Comment by denizyuret** [comment]
@nmutlu98 thank you. But I only see one of the listed publications on the ML publications page, do you have any idea why the others do not show up?

**Comment by nmutlu98** [comment]
My fault... Now they should be there.

**Comment by denizyuret** [comment]
Thanks again. @fguney - our publications do not have links. Most should be accessible online, should we put links? @nmutlu98 coban2017 referansinin yayinlandigi yer cikmamis, bunlari otomatik hallediyorsak konferanslarda kullanilan "booktitle" field dogru handle edilmiyor olabilir.

**Comment by nmutlu98** [comment]
I fixed the link trees in publications page and in the subpages of research pages.
