### ISSUE TITLE
new seminar video

### ISSUE THREAD

**Issue by denizyuret** [kuisailab/ai-media-group#44]
Here is a video and info about the seminar I gave yesterday. It was a recorded sample lecture for prospective MSc Data Science (Non-Thesis) applicants followed by a live QA session. Let's put it somewhere appropriate. Please contact Melissa for any necessary info about the seminar.

```
From: Melissa Abache <MABACHE@ku.edu.tr>

Dear Deniz Hoca,

Many thanks for your time yesterday. I think it went well in terms of participation (50-70 during the event) and the questions asked by participants.

You can find the video below to embed on the KUIS AI Lab website as you requested and to be shared on social media

https://youtu.be/hxFp2l5YyXg

@Özgür Hoca and Hande Hanım; I’ve added the webinar stats and comments to our central Google sheet Graduate programs promotion activities Dec 2020-Dec 2021

Best,
Melissa
```

**Comment by denizyuret** [comment]
Bu da ayni lecture ama sonunda biraz daha heyecanli bir soru-cevap session var, bunu tercih edebiliriz:

Merhaba Deniz Hocam,

Sonunda seminer kayıtlarımız GLODEM web sayfasında yayınlandı, aşağıdaki linkten ulaşabilirsiniz:
https://glodem.ku.edu.tr/events/third-deep-learning-revolution/

Ayrıca GLODEM YouTube kanalı üzerinden de paylaştı: 
https://www.youtube.com/watch?v=7osulihDNrA&feature=emb_logo

Güzel bir haftasonu dileklerimle...

En içten sevgi ve saygılarımla,

Merih

**Comment by fguney** [comment]
Bu benim actigim yeni issue'ya merge edilebilir: "add talks.."
