### ISSUE TITLE
Activity Report

### ISSUE THREAD

**Issue by denizyuret** [kuisailab/ai-media-group#65]
Let's put links to our new reports (PDFs) under the About tab:
- 2020-2021 Executive Summary
- 2020-2021 Activity Report

**Comment by denizyuret** [comment]
Burada tab'lerde gorunmeme problemimiz var cozebildik mi?

**Comment by fguney** [comment]
yok, gorunmemesine karar verdik, her sene eklenecegi icin raporlar tab uzar gider gibi geldi.

**Comment by denizyuret** [comment]
En son seneninkini tutariz diye dusunmustum. Digerlerini arsivleriz menu'de
kolay accessible olmasina gerek kalmaz. Fakat su anki haliyle disaridan
bizi merak eden bir insanin kolay ulasabilecegi bir yerde degil.
